version: '3.8'

services:
  ocr-api:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN:-your_secret_token_here}
      - PORT=${PORT:-5000}
    volumes:
      - ./logs:/app/logs:rw
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-5000}/fx_ocr"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 